---
trust-domain: "taskgraph"
task-priority: low

taskgraph:
  cached-task-prefix: "taskgraph.v2.mozilla-taskgraph"
  repositories:
    mozilla_taskgraph:
      name: "mozilla-taskgraph"

workers:
  aliases:
    b-linux:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    t-linux-large:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
